"""Repository ports for workspace entity CRUD (TKT-C02-02)."""

from __future__ import annotations

from typing import Any, Protocol

from simulator.domain.models.simulation_entities import (
    SimulatedApplication,
    TargetDefinition,
    TaskDefinitionSRS,
)


class ApplicationRepositoryPort(Protocol):
    """CRUD for SimulatedApplication with reference integrity."""

    def get(self, app_id: str) -> SimulatedApplication | None: ...
    def list_all(self) -> list[SimulatedApplication]: ...
    def save(self, entity: SimulatedApplication) -> None: ...
    def delete(self, app_id: str) -> None: ...


class TargetRepositoryPort(Protocol):
    """CRUD for TargetDefinition; application_ref must exist."""

    def get(self, target_id: str) -> TargetDefinition | None: ...
    def list_all(self) -> list[TargetDefinition]: ...
    def save(self, entity: TargetDefinition) -> None: ...
    def delete(self, target_id: str) -> None: ...


class TaskRepositoryPort(Protocol):
    """CRUD for TaskDefinitionSRS; application_ref must exist."""

    def get(self, task_id: str) -> TaskDefinitionSRS | None: ...
    def list_all(self) -> list[TaskDefinitionSRS]: ...
    def save(self, entity: TaskDefinitionSRS) -> None: ...
    def delete(self, task_id: str) -> None: ...
